[ 2025-08-03 22:19:38,994 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.29.166:5000
[ 2025-08-03 22:19:38,994 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-08-03 22:20:16,982 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:20:16,985 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:20:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:20:17,025 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:20:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2025-08-03 22:23:37,149 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:23:37,151 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:23:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:23:39,638 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:23:39,640 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:23:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:23:40,582 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:23:40,583 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:23:40] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:23:40,781 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:23:40,782 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:23:40] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:23:41,005 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:23:41,006 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:23:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:23:56,610 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:23:56,611 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:23:56] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:27:16,982 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:27:16,983 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:27:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:27:17,851 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:27:17,852 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:27:17] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:27:18,044 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:27:18,046 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:27:18] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:27:18,273 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:27:18,275 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:27:18] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:27:24,371 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:27:24,373 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:27:24] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:27:28,681 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    return render_template('index.html')
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:27:28,683 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:27:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:10,666 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:10,678 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:12,642 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:12,644 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:12] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:13,485 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:13,487 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:13,693 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:13,696 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:13,890 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:13,891 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:14,097 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:14,099 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:31:14,314 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:31:14,315 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:31:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:34:19,860 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:34:19,862 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:34:19] "[35m[1mGET / HTTP/1.1[0m" 500 -
[ 2025-08-03 22:34:28,174 ] 838 Prediction_application - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "Prediction_application.py", line 21, in index
    @app.route('/predictdata', methods=['GET', 'POST'])
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\rroha\OneDrive\Desktop\Raj\ML_Project_Industrial\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[ 2025-08-03 22:34:28,176 ] 97 werkzeug - INFO - 127.0.0.1 - - [03/Aug/2025 22:34:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
